import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated code, not source:
    "lib/types/database.ts",
    // Supabase CLI-managed local stack artifacts (Edge Runtime bundle etc.),
    // regenerated by `supabase start` and not part of the app source tree.
    "supabase/.temp/**",
    // Deno-only Edge Function source — uses Deno globals, jsr:/npm: specifiers,
    // and .ts import extensions that ESLint's Next/Node parser can't handle.
    "supabase/functions/**",
    // Sibling git worktrees for other branches of a second checkout of this
    // same repo, already git-ignored. Each has its own lint script.
    ".worktrees/**",
  ]),
]);

export default eslintConfig;
